export const DataTicket = [
  {
    ticket_id: 1,
    customer_name: "Mahalia McClunaghan",
    customer_email: "mmcclunaghan0@themeforest.net",
    ticket_price: 117.49,
    payment_method: "credit card",
    payment_date: "11/12/2022",
    payment_status: "completed",
    seat_number: "C1",
    event_date: "10/22/2022",
  },
  {
    ticket_id: 2,
    customer_name: "Ianthe McHan",
    customer_email: "imchan1@huffingtonpost.com",
    ticket_price: 891.93,
    payment_method: "credit card",
    payment_date: "1/31/2022",
    payment_status: "failed",
    seat_number: "C2",
    event_date: "12/14/2022",
  },
  {
    ticket_id: 3,
    customer_name: "Ronny Burlingame",
    customer_email: "rburlingame2@liveinternet.ru",
    ticket_price: 520.14,
    payment_method: "debit card",
    payment_date: "12/9/2022",
    payment_status: "completed",
    seat_number: "A1",
    event_date: "8/1/2022",
  },
  {
    ticket_id: 4,
    customer_name: "Blaine Havercroft",
    customer_email: "bhavercroft3@npr.org",
    ticket_price: 206.35,
    payment_method: "PayPal",
    payment_date: "8/23/2022",
    payment_status: "completed",
    seat_number: "C2",
    event_date: "5/21/2022",
  },
  {
    ticket_id: 5,
    customer_name: "Rivy Galbreath",
    customer_email: "rgalbreath4@goo.ne.jp",
    ticket_price: 359.26,
    payment_method: "debit card",
    payment_date: "11/14/2022",
    payment_status: "failed",
    seat_number: "B1",
    event_date: "11/9/2022",
  },
  {
    ticket_id: 6,
    customer_name: "Reeba Cottey",
    customer_email: "rcottey5@walmart.com",
    ticket_price: 884.86,
    payment_method: "credit card",
    payment_date: "4/23/2022",
    payment_status: "failed",
    seat_number: "A1",
    event_date: "4/25/2022",
  },
  {
    ticket_id: 7,
    customer_name: "Celka McArtan",
    customer_email: "cmcartan6@acquirethisname.com",
    ticket_price: 613.45,
    payment_method: "credit card",
    payment_date: "3/30/2022",
    payment_status: "failed",
    seat_number: "B1",
    event_date: "2/25/2022",
  },
  {
    ticket_id: 8,
    customer_name: "Lisle Draisey",
    customer_email: "ldraisey7@behance.net",
    ticket_price: 285.87,
    payment_method: "debit card",
    payment_date: "2/6/2022",
    payment_status: "completed",
    seat_number: "B2",
    event_date: "8/3/2022",
  },
  {
    ticket_id: 9,
    customer_name: "Merry Dilawey",
    customer_email: "mdilawey8@imgur.com",
    ticket_price: 928.19,
    payment_method: "debit card",
    payment_date: "7/22/2022",
    payment_status: "failed",
    seat_number: "B2",
    event_date: "3/18/2022",
  },
  {
    ticket_id: 10,
    customer_name: "Wenona Romei",
    customer_email: "wromei9@vk.com",
    ticket_price: 42.95,
    payment_method: "credit card",
    payment_date: "1/3/2022",
    payment_status: "completed",
    seat_number: "C2",
    event_date: "2/8/2022",
  },
  {
    ticket_id: 11,
    customer_name: "Shepperd Licas",
    customer_email: "slicasa@histats.com",
    ticket_price: 613.74,
    payment_method: "PayPal",
    payment_date: "6/15/2022",
    payment_status: "pending",
    seat_number: "A2",
    event_date: "9/17/2022",
  },
  {
    ticket_id: 12,
    customer_name: "Tanner Scryne",
    customer_email: "tscryneb@vk.com",
    ticket_price: 950.12,
    payment_method: "PayPal",
    payment_date: "6/15/2022",
    payment_status: "pending",
    seat_number: "B2",
    event_date: "8/30/2022",
  },
  {
    ticket_id: 13,
    customer_name: "Georgie Reggio",
    customer_email: "greggioc@geocities.com",
    ticket_price: 924.94,
    payment_method: "PayPal",
    payment_date: "8/20/2022",
    payment_status: "pending",
    seat_number: "C1",
    event_date: "11/27/2022",
  },
  {
    ticket_id: 14,
    customer_name: "Sonni Colbrun",
    customer_email: "scolbrund@foxnews.com",
    ticket_price: 515.16,
    payment_method: "debit card",
    payment_date: "12/7/2022",
    payment_status: "failed",
    seat_number: "A2",
    event_date: "5/7/2022",
  },
  {
    ticket_id: 15,
    customer_name: "Sly Loughead",
    customer_email: "slougheade@nps.gov",
    ticket_price: 292.71,
    payment_method: "debit card",
    payment_date: "10/11/2022",
    payment_status: "completed",
    seat_number: "C2",
    event_date: "4/22/2022",
  },
  {
    ticket_id: 16,
    customer_name: "Judas Lythgoe",
    customer_email: "jlythgoef@nps.gov",
    ticket_price: 848.46,
    payment_method: "PayPal",
    payment_date: "6/4/2022",
    payment_status: "pending",
    seat_number: "C1",
    event_date: "11/11/2022",
  },
  {
    ticket_id: 17,
    customer_name: "Dolorita Erley",
    customer_email: "derleyg@tumblr.com",
    ticket_price: 573.28,
    payment_method: "PayPal",
    payment_date: "12/4/2022",
    payment_status: "failed",
    seat_number: "C2",
    event_date: "4/3/2022",
  },
  {
    ticket_id: 18,
    customer_name: "Moe Colwell",
    customer_email: "mcolwellh@nydailynews.com",
    ticket_price: 930.1,
    payment_method: "credit card",
    payment_date: "11/10/2022",
    payment_status: "failed",
    seat_number: "A1",
    event_date: "1/1/2022",
  },
  {
    ticket_id: 19,
    customer_name: "Inessa Cocke",
    customer_email: "icockei@last.fm",
    ticket_price: 702.54,
    payment_method: "debit card",
    payment_date: "11/9/2022",
    payment_status: "failed",
    seat_number: "C2",
    event_date: "1/30/2022",
  },
  {
    ticket_id: 20,
    customer_name: "Joelie Inkle",
    customer_email: "jinklej@statcounter.com",
    ticket_price: 821.7,
    payment_method: "credit card",
    payment_date: "8/23/2022",
    payment_status: "failed",
    seat_number: "B2",
    event_date: "5/7/2022",
  },
  {
    ticket_id: 21,
    customer_name: "Antonetta Petofi",
    customer_email: "apetofik@mail.ru",
    ticket_price: 9.46,
    payment_method: "PayPal",
    payment_date: "5/6/2022",
    payment_status: "failed",
    seat_number: "C1",
    event_date: "5/9/2022",
  },
  {
    ticket_id: 22,
    customer_name: "Layney Josskovitz",
    customer_email: "ljosskovitzl@un.org",
    ticket_price: 922.96,
    payment_method: "credit card",
    payment_date: "9/3/2022",
    payment_status: "failed",
    seat_number: "A2",
    event_date: "10/22/2022",
  },
  {
    ticket_id: 23,
    customer_name: "Say Kleinerman",
    customer_email: "skleinermanm@angelfire.com",
    ticket_price: 810.24,
    payment_method: "debit card",
    payment_date: "10/4/2022",
    payment_status: "failed",
    seat_number: "B1",
    event_date: "1/10/2022",
  },
  {
    ticket_id: 24,
    customer_name: "Alena Rohmer",
    customer_email: "arohmern@businesswire.com",
    ticket_price: 507.08,
    payment_method: "credit card",
    payment_date: "5/6/2022",
    payment_status: "completed",
    seat_number: "A1",
    event_date: "11/17/2022",
  },
  {
    ticket_id: 25,
    customer_name: "Shay Toffolini",
    customer_email: "stoffolinio@alibaba.com",
    ticket_price: 950.44,
    payment_method: "credit card",
    payment_date: "5/24/2022",
    payment_status: "pending",
    seat_number: "A2",
    event_date: "3/28/2022",
  },
  {
    ticket_id: 26,
    customer_name: "Harrie Klishin",
    customer_email: "hklishinp@cam.ac.uk",
    ticket_price: 594.13,
    payment_method: "PayPal",
    payment_date: "5/27/2022",
    payment_status: "pending",
    seat_number: "A1",
    event_date: "2/25/2022",
  },
  {
    ticket_id: 27,
    customer_name: "Saxe Benian",
    customer_email: "sbenianq@virginia.edu",
    ticket_price: 350.5,
    payment_method: "debit card",
    payment_date: "3/3/2022",
    payment_status: "failed",
    seat_number: "B2",
    event_date: "11/22/2022",
  },
  {
    ticket_id: 28,
    customer_name: "Tobi Patinkin",
    customer_email: "tpatinkinr@chronoengine.com",
    ticket_price: 369.13,
    payment_method: "PayPal",
    payment_date: "11/29/2022",
    payment_status: "completed",
    seat_number: "A1",
    event_date: "8/11/2022",
  },
  {
    ticket_id: 29,
    customer_name: "Saunderson Behnke",
    customer_email: "sbehnkes@nifty.com",
    ticket_price: 258.21,
    payment_method: "PayPal",
    payment_date: "11/12/2022",
    payment_status: "completed",
    seat_number: "A1",
    event_date: "7/28/2022",
  },
  {
    ticket_id: 30,
    customer_name: "Maire Mickleborough",
    customer_email: "mmickleborought@google.de",
    ticket_price: 366.71,
    payment_method: "PayPal",
    payment_date: "11/20/2022",
    payment_status: "completed",
    seat_number: "B1",
    event_date: "3/17/2022",
  },
  {
    ticket_id: 31,
    customer_name: "Kitti Wales",
    customer_email: "kwalesu@prlog.org",
    ticket_price: 620.91,
    payment_method: "credit card",
    payment_date: "12/24/2022",
    payment_status: "pending",
    seat_number: "B1",
    event_date: "12/4/2022",
  },
  {
    ticket_id: 32,
    customer_name: "Wildon Swainson",
    customer_email: "wswainsonv@nymag.com",
    ticket_price: 242.76,
    payment_method: "PayPal",
    payment_date: "7/19/2022",
    payment_status: "pending",
    seat_number: "A2",
    event_date: "1/16/2022",
  },
  {
    ticket_id: 33,
    customer_name: "Marilin McAlpin",
    customer_email: "mmcalpinw@virginia.edu",
    ticket_price: 692.03,
    payment_method: "PayPal",
    payment_date: "3/22/2022",
    payment_status: "completed",
    seat_number: "A2",
    event_date: "8/3/2022",
  },
  {
    ticket_id: 34,
    customer_name: "Fonz Garwood",
    customer_email: "fgarwoodx@instagram.com",
    ticket_price: 940.5,
    payment_method: "debit card",
    payment_date: "3/28/2022",
    payment_status: "pending",
    seat_number: "A2",
    event_date: "7/7/2022",
  },
  {
    ticket_id: 35,
    customer_name: "Torrence Rogers",
    customer_email: "trogersy@hatena.ne.jp",
    ticket_price: 120.67,
    payment_method: "credit card",
    payment_date: "3/25/2022",
    payment_status: "failed",
    seat_number: "B1",
    event_date: "5/18/2022",
  },
  {
    ticket_id: 36,
    customer_name: "Dalt Andrea",
    customer_email: "dandreaz@aboutads.info",
    ticket_price: 329.17,
    payment_method: "credit card",
    payment_date: "5/26/2022",
    payment_status: "failed",
    seat_number: "C1",
    event_date: "8/24/2022",
  },
  {
    ticket_id: 37,
    customer_name: "Nickie Shambroke",
    customer_email: "nshambroke10@paypal.com",
    ticket_price: 664.65,
    payment_method: "PayPal",
    payment_date: "6/10/2022",
    payment_status: "pending",
    seat_number: "A1",
    event_date: "2/23/2022",
  },
  {
    ticket_id: 38,
    customer_name: "Pearline Taudevin",
    customer_email: "ptaudevin11@examiner.com",
    ticket_price: 369.53,
    payment_method: "debit card",
    payment_date: "8/7/2022",
    payment_status: "pending",
    seat_number: "C1",
    event_date: "1/26/2022",
  },
  {
    ticket_id: 39,
    customer_name: "Kimmi Borland",
    customer_email: "kborland12@vkontakte.ru",
    ticket_price: 726.03,
    payment_method: "PayPal",
    payment_date: "10/28/2022",
    payment_status: "completed",
    seat_number: "C1",
    event_date: "9/10/2022",
  },
  {
    ticket_id: 40,
    customer_name: "Pansy Santori",
    customer_email: "psantori13@opensource.org",
    ticket_price: 523.1,
    payment_method: "PayPal",
    payment_date: "2/26/2022",
    payment_status: "failed",
    seat_number: "C2",
    event_date: "7/20/2022",
  },
  {
    ticket_id: 41,
    customer_name: "Dorian Fairfoull",
    customer_email: "dfairfoull14@sitemeter.com",
    ticket_price: 965.54,
    payment_method: "credit card",
    payment_date: "11/12/2022",
    payment_status: "pending",
    seat_number: "C1",
    event_date: "1/13/2022",
  },
  {
    ticket_id: 42,
    customer_name: "Duffy Duchenne",
    customer_email: "dduchenne15@google.it",
    ticket_price: 346.38,
    payment_method: "PayPal",
    payment_date: "8/4/2022",
    payment_status: "failed",
    seat_number: "B1",
    event_date: "7/28/2022",
  },
  {
    ticket_id: 43,
    customer_name: "Maegan Quant",
    customer_email: "mquant16@mapy.cz",
    ticket_price: 167.94,
    payment_method: "PayPal",
    payment_date: "3/10/2022",
    payment_status: "failed",
    seat_number: "B1",
    event_date: "8/5/2022",
  },
  {
    ticket_id: 44,
    customer_name: "Francoise Dalziel",
    customer_email: "fdalziel17@seesaa.net",
    ticket_price: 726.55,
    payment_method: "credit card",
    payment_date: "12/25/2022",
    payment_status: "failed",
    seat_number: "C2",
    event_date: "6/14/2022",
  },
  {
    ticket_id: 45,
    customer_name: "Marietta Bolan",
    customer_email: "mbolan18@ucsd.edu",
    ticket_price: 530.26,
    payment_method: "credit card",
    payment_date: "5/3/2022",
    payment_status: "completed",
    seat_number: "B1",
    event_date: "12/30/2022",
  },
  {
    ticket_id: 46,
    customer_name: "Paddie Bowdon",
    customer_email: "pbowdon19@mozilla.org",
    ticket_price: 854.7,
    payment_method: "credit card",
    payment_date: "4/3/2022",
    payment_status: "completed",
    seat_number: "C1",
    event_date: "11/8/2022",
  },
  {
    ticket_id: 47,
    customer_name: "Gennie Whybrow",
    customer_email: "gwhybrow1a@sciencedirect.com",
    ticket_price: 714.21,
    payment_method: "credit card",
    payment_date: "4/28/2022",
    payment_status: "failed",
    seat_number: "B2",
    event_date: "9/17/2022",
  },
  {
    ticket_id: 48,
    customer_name: "Sada Jone",
    customer_email: "sjone1b@google.es",
    ticket_price: 691.64,
    payment_method: "credit card",
    payment_date: "12/20/2022",
    payment_status: "completed",
    seat_number: "B2",
    event_date: "4/1/2022",
  },
  {
    ticket_id: 49,
    customer_name: "Cornall Eade",
    customer_email: "ceade1c@multiply.com",
    ticket_price: 85.53,
    payment_method: "credit card",
    payment_date: "5/10/2022",
    payment_status: "completed",
    seat_number: "A1",
    event_date: "2/7/2022",
  },
  {
    ticket_id: 50,
    customer_name: "Cecilia A'Barrow",
    customer_email: "cabarrow1d@nps.gov",
    ticket_price: 938.25,
    payment_method: "PayPal",
    payment_date: "8/11/2022",
    payment_status: "failed",
    seat_number: "B1",
    event_date: "6/28/2022",
  },
];
